apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab
  labels:
    app: paper
  name: paper-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paper
  template:
    metadata:
      labels:
        app: paper
    spec:
      containers:
      - image: 192.168.11.3:10000/ci/paper:latest.
        name: paper-test
        ports:
        - containerPort: 5000
          name: flask
          protocol: TCP
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: paper-test-svc
  namespace: lab
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30010
      protocol: TCP
      targetPort: 5000
  selector:
    app: paper